package i18n

// translations is the single source for all localised strings.
// Key convention: page.section.element  (e.g. "home.hero.title")
// Fallback: if a key or locale is missing the EN value is used.
var translations = map[string]map[Locale]string{

	// ── Language switcher ──────────────────────────────────────────────────
	"lang.label": {EN: "Language", ES: "Idioma", FR: "Langue", DE: "Sprache"},

	// ── Navigation ─────────────────────────────────────────────────────────
	"nav.home":         {EN: "Home", ES: "Inicio", FR: "Accueil", DE: "Startseite"},
	"nav.forms":        {EN: "Forms", ES: "Formularios", FR: "Formulaires", DE: "Formulare"},
	"nav.registration": {EN: "Registration", ES: "Registro", FR: "Inscription", DE: "Registrierung"},
	"nav.components":   {EN: "Components", ES: "Componentes", FR: "Composants", DE: "Komponenten"},
	"nav.docs":         {EN: "Docs", ES: "Docs", FR: "Docs", DE: "Docs"},
	"nav.theming":      {EN: "Theming", ES: "Temas", FR: "Thèmes", DE: "Design"},
	"nav.telemetry":    {EN: "Telemetry", ES: "Telemetría", FR: "Télémétrie", DE: "Telemetrie"},
	"nav.dashboard":    {EN: "Dashboard", ES: "Panel", FR: "Tableau de bord", DE: "Dashboard"},
	"nav.table":        {EN: "Table", ES: "Tabla", FR: "Table", DE: "Tabelle"},
	"nav.profile":      {EN: "Profile", ES: "Perfil", FR: "Profil", DE: "Profil"},
	"nav.signin":       {EN: "Sign In", ES: "Iniciar sesión", FR: "Connexion", DE: "Anmelden"},
	"nav.logout":       {EN: "Logout", ES: "Cerrar sesión", FR: "Déconnexion", DE: "Abmelden"},
	"nav.open":         {EN: "Open navigation", ES: "Abrir navegación", FR: "Ouvrir la navigation", DE: "Navigation öffnen"},
	"nav.close":        {EN: "Close navigation", ES: "Cerrar navegación", FR: "Fermer la navigation", DE: "Navigation schließen"},

	// ── Footer ─────────────────────────────────────────────────────────────
	"footer.tagline":  {EN: "Client-side security defaults. Zero dependencies. No CAPTCHA required.", ES: "Seguridad por defecto en el cliente. Sin dependencias. Sin CAPTCHA.", FR: "Sécurité côté client par défaut. Zéro dépendances. Sans CAPTCHA.", DE: "Client-seitige Sicherheit als Standard. Null Abhängigkeiten. Kein CAPTCHA erforderlich."},
	"footer.resources": {EN: "Resources", ES: "Recursos", FR: "Ressources", DE: "Ressourcen"},
	"footer.community": {EN: "Community", ES: "Comunidad", FR: "Communauté", DE: "Community"},
	"footer.legal":     {EN: "Legal", ES: "Legal", FR: "Légal", DE: "Rechtliches"},
	"footer.cookies":   {EN: "Cookie Policy", ES: "Política de cookies", FR: "Politique de cookies", DE: "Cookie-Richtlinie"},
	"footer.docs":      {EN: "Documentation", ES: "Documentación", FR: "Documentation", DE: "Dokumentation"},
	"footer.forms":     {EN: "Form Components", ES: "Componentes de formulario", FR: "Composants de formulaire", DE: "Formularkomponenten"},
	"footer.reg_demo":  {EN: "Registration Demo", ES: "Demo de registro", FR: "Démo d'inscription", DE: "Registrierungs-Demo"},
	"footer.copyright": {EN: "© 2025 Secure-UI. All rights reserved. Built with zero dependencies.", ES: "© 2025 Secure-UI. Todos los derechos reservados. Creado sin dependencias.", FR: "© 2025 Secure-UI. Tous droits réservés. Construit sans dépendances.", DE: "© 2025 Secure-UI. Alle Rechte vorbehalten. Mit null Abhängigkeiten erstellt."},

	// ── Home — Hero ────────────────────────────────────────────────────────
	"home.hero.eyebrow":     {EN: "No CAPTCHA required", ES: "Sin CAPTCHA", FR: "Sans CAPTCHA", DE: "Kein CAPTCHA"},
	"home.hero.line1":       {EN: "Security-hardened", ES: "Componentes", FR: "Composants", DE: "Sicherheitsgehärtete"},
	"home.hero.line2":       {EN: "components.", ES: "de seguridad reforzada.", FR: "sécurisés par défaut.", DE: "Komponenten."},
	"home.hero.line3":       {EN: "One tag. No config.", ES: "Una etiqueta. Sin config.", FR: "Une balise. Zéro config.", DE: "Ein Tag. Kein Setup."},
	"home.hero.desc":        {EN: "Bot detection without the vendor tax. CSRF, XSS, and audit logging active on every component by default. Works with any framework or server-rendered HTML.", ES: "Detección de bots sin costes de proveedor. CSRF, XSS y registro de auditoría activos en cada componente por defecto. Compatible con cualquier framework o HTML renderizado en servidor.", FR: "Détection de bots sans frais de fournisseur. CSRF, XSS et journalisation d'audit actifs sur chaque composant par défaut. Compatible avec tout framework ou HTML rendu côté serveur.", DE: "Bot-Erkennung ohne Anbietergebühren. CSRF, XSS und Audit-Logging standardmäßig auf jeder Komponente aktiv. Funktioniert mit jedem Framework oder server-seitig gerendertem HTML."},
	"home.hero.cta_explore": {EN: "Get started", ES: "Comenzar", FR: "Démarrer", DE: "Loslegen"},
	"home.hero.cta_start":   {EN: "See live demos", ES: "Ver demos en vivo", FR: "Voir les démos", DE: "Live-Demos ansehen"},
	"home.hero.install":     {EN: "npm i secure-ui-components", ES: "npm i secure-ui-components", FR: "npm i secure-ui-components", DE: "npm i secure-ui-components"},
	"home.hero.trust_deps":  {EN: "Zero dependencies", ES: "Sin dependencias", FR: "Zéro dépendances", DE: "Null Abhängigkeiten"},
	"home.hero.trust_mit":   {EN: "MIT License", ES: "Licencia MIT", FR: "Licence MIT", DE: "MIT-Lizenz"},
	"home.hero.trust_fw":    {EN: "Any framework", ES: "Cualquier framework", FR: "Tout framework", DE: "Jedes Framework"},
	"home.hero.trust_comp":  {EN: "9 components", ES: "9 componentes", FR: "9 composants", DE: "9 Komponenten"},

	// ── Home — Stats ───────────────────────────────────────────────────────
	"home.stats.deps":    {EN: "runtime dependencies", ES: "dependencias en runtime", FR: "dépendances runtime", DE: "Laufzeitabhängigkeiten"},
	"home.stats.signals": {EN: "behavioral signals", ES: "señales de comportamiento", FR: "signaux comportementaux", DE: "Verhaltenssignale"},
	"home.stats.signed":  {EN: "signed telemetry", ES: "telemetría firmada", FR: "télémétrie signée", DE: "signierte Telemetrie"},
	"home.stats.owasp":   {EN: "OWASP coverage mapped", ES: "cobertura OWASP mapeada", FR: "couverture OWASP mappée", DE: "OWASP-Abdeckung kartiert"},

	// ── Home — Demo ────────────────────────────────────────────────────────
	"home.demo.label":      {EN: "Try it now", ES: "Pruébalo ahora", FR: "Essayez maintenant", DE: "Jetzt ausprobieren"},
	"home.demo.heading":    {EN: "Touch the components.", ES: "Prueba los componentes.", FR: "Touchez les composants.", DE: "Testen Sie die Komponenten."},
	"home.demo.subheading": {EN: "See security in action.", ES: "Ve la seguridad en acción.", FR: "Voyez la sécurité en action.", DE: "Sicherheit in Aktion erleben."},
	"home.demo.body":       {EN: "These are live secure-input and secure-form components. CSRF token injection, XSS sanitization, and audit logging are active. Inspect the DOM — the Shadow DOM keeps the internal structure isolated.", ES: "Estos son componentes secure-input y secure-form en vivo. La inyección de tokens CSRF, la sanitización XSS y el registro de auditoría están activos. Inspecciona el DOM — el Shadow DOM mantiene aislada la estructura interna.", FR: "Ce sont des composants secure-input et secure-form en direct. L'injection de jetons CSRF, la désinfection XSS et la journalisation d'audit sont actives. Inspectez le DOM — le Shadow DOM isole la structure interne.", DE: "Dies sind live secure-input- und secure-form-Komponenten. CSRF-Token-Injektion, XSS-Sanitierung und Audit-Logging sind aktiv. Untersuchen Sie das DOM — das Shadow DOM hält die interne Struktur isoliert."},
	"home.demo.link":       {EN: "See all 9 components", ES: "Ver los 9 componentes", FR: "Voir les 9 composants", DE: "Alle 9 Komponenten ansehen"},
	"home.demo.panel_title": {EN: "secure-form + secure-input", ES: "secure-form + secure-input", FR: "secure-form + secure-input", DE: "secure-form + secure-input"},
	"home.demo.panel_live":  {EN: "Live", ES: "En vivo", FR: "En direct", DE: "Live"},
	"home.demo.submit":      {EN: "Submit securely", ES: "Enviar de forma segura", FR: "Envoyer en sécurité", DE: "Sicher absenden"},

	// ── Home — Features ────────────────────────────────────────────────────
	"home.feat.eyebrow": {EN: "What sets it apart", ES: "Lo que lo diferencia", FR: "Ce qui le distingue", DE: "Was es unterscheidet"},
	"home.feat.title":   {EN: "Not just a UI library", ES: "Más que una biblioteca UI", FR: "Pas seulement une bibliothèque UI", DE: "Mehr als eine UI-Bibliothek"},
	"home.feat.desc":    {EN: "Shadow DOM isolation, behavioral telemetry, and audit logging — capabilities standard UI libraries cannot add without a full architectural rewrite.", ES: "Aislamiento Shadow DOM, telemetría de comportamiento y registro de auditoría — capacidades que las bibliotecas UI estándar no pueden añadir sin una reescritura arquitectónica completa.", FR: "Isolation Shadow DOM, télémétrie comportementale et journalisation d'audit — des capacités que les bibliothèques UI standard ne peuvent pas ajouter sans réécriture architecturale.", DE: "Shadow-DOM-Isolation, Verhaltens-Telemetrie und Audit-Logging — Fähigkeiten, die Standard-UI-Bibliotheken ohne vollständige Architekturüberarbeitung nicht hinzufügen können."},
	"home.feat.shadowdom.title": {EN: "Closed Shadow DOM", ES: "Shadow DOM cerrado", FR: "Shadow DOM fermé", DE: "Geschlossenes Shadow DOM"},
	"home.feat.shadowdom.desc":  {EN: "Field values live inside a closed shadow root. Scripts, extensions, and devtools cannot read or tamper with the internal DOM. Validation state stays private until submission.", ES: "Los valores de campo viven dentro de un shadow root cerrado. Los scripts, extensiones y devtools no pueden leer ni manipular el DOM interno.", FR: "Les valeurs de champ vivent dans un shadow root fermé. Les scripts, extensions et devtools ne peuvent pas lire ni modifier le DOM interne.", DE: "Feldwerte leben in einem geschlossenen Shadow Root. Skripte, Erweiterungen und Devtools können das interne DOM nicht lesen oder manipulieren."},

	"home.feat.csrf.title":       {EN: "Automatic CSRF Protection", ES: "Protección CSRF automática", FR: "Protection CSRF automatique", DE: "Automatischer CSRF-Schutz"},
	"home.feat.csrf.desc":        {EN: "All forms automatically include CSRF tokens. No manual token management required.", ES: "Todos los formularios incluyen automáticamente tokens CSRF. No se requiere gestión manual de tokens.", FR: "Tous les formulaires incluent automatiquement des jetons CSRF. Aucune gestion manuelle des jetons requise.", DE: "Alle Formulare enthalten automatisch CSRF-Token. Keine manuelle Token-Verwaltung erforderlich."},
	"home.feat.validation.title": {EN: "Layered Validation", ES: "Validación en capas", FR: "Validation en couches", DE: "Mehrschichtige Validierung"},
	"home.feat.validation.desc":  {EN: "Client-side feedback, server-side authority. Defence in depth without the boilerplate.", ES: "Retroalimentación del lado del cliente, autoridad del lado del servidor. Defensa en profundidad sin repeticiones.", FR: "Retour côté client, autorité côté serveur. Défense en profondeur sans boilerplate.", DE: "Client-seitiges Feedback, server-seitige Autorität. Defense-in-Depth ohne Boilerplate."},
	"home.feat.xss.title":        {EN: "Input Sanitization", ES: "Sanitización de entradas", FR: "Assainissement des entrées", DE: "Eingabe-Sanitierung"},
	"home.feat.xss.desc":         {EN: "XSS prevention built into every component. Automatic encoding, script stripping, handler removal.", ES: "Prevención XSS integrada en cada componente. Codificación automática, eliminación de scripts y manejadores.", FR: "Prévention XSS intégrée dans chaque composant. Encodage automatique, suppression de scripts et de gestionnaires.", DE: "XSS-Prävention in jede Komponente integriert. Automatische Kodierung, Script-Entfernung, Handler-Löschung."},
	"home.feat.defaults.title":   {EN: "Secure Defaults", ES: "Valores predeterminados seguros", FR: "Valeurs par défaut sécurisées", DE: "Sichere Standardwerte"},
	"home.feat.defaults.desc":    {EN: "Strict CSP, secure headers, safe cookies, and closed Shadow DOM isolation — active from first render.", ES: "CSP estricto, cabeceras seguras, cookies seguras y aislamiento Shadow DOM cerrado — activos desde el primer renderizado.", FR: "CSP strict, en-têtes sécurisés, cookies sécurisés et isolation Shadow DOM fermée — actifs dès le premier rendu.", DE: "Strenge CSP, sichere Header, sichere Cookies und geschlossene Shadow DOM-Isolation — ab dem ersten Rendering aktiv."},
	"home.feat.ssot.title":       {EN: "Single Source of Truth", ES: "Única fuente de verdad", FR: "Source unique de vérité", DE: "Einzige Wahrheitsquelle"},
	"home.feat.ssot.desc":        {EN: "Server owns all persistent state and security decisions. Components manage only transient UI state.", ES: "El servidor posee todo el estado persistente y las decisiones de seguridad. Los componentes solo gestionan el estado transitorio de la interfaz.", FR: "Le serveur possède tout l'état persistant et les décisions de sécurité. Les composants ne gèrent que l'état transitoire de l'interface.", DE: "Der Server besitzt alle persistenten Zustände und Sicherheitsentscheidungen. Komponenten verwalten nur transitorische UI-Zustände."},
	"home.feat.audit.title":      {EN: "Audit-Ready Logging", ES: "Registro listo para auditoría", FR: "Journalisation prête pour l'audit", DE: "Audit-bereites Logging"},
	"home.feat.audit.desc":       {EN: "Client-side security events logged on every component. Use the audit trail to identify suspicious patterns, flag abuse, and meet compliance requirements.", ES: "Eventos de seguridad del lado del cliente registrados en cada componente. Usa el registro de auditoría para identificar patrones sospechosos, detectar abuso y cumplir requisitos de conformidad.", FR: "Événements de sécurité côté client journalisés sur chaque composant. Utilisez la piste d'audit pour identifier les comportements suspects, signaler les abus et satisfaire aux exigences de conformité.", DE: "Client-seitige Sicherheitsereignisse auf jeder Komponente protokolliert. Nutzen Sie das Audit-Trail zur Erkennung verdächtiger Muster, Missbrauchs-Flagging und Compliance."},

	"home.feat.captcha.title": {EN: "Behavioral Telemetry", ES: "Telemetría de comportamiento", FR: "Télémétrie comportementale", DE: "Verhaltens-Telemetrie"},
	"home.feat.captcha.desc":  {EN: "Passive behavioral signals catch commodity bots silently. Score every submission — only trigger a CAPTCHA challenge for the small percentage that looks suspicious. Real users never see a puzzle.", ES: "Las señales de comportamiento pasivas detectan bots silenciosamente. Puntúa cada envío — solo activa un CAPTCHA para el pequeño porcentaje sospechoso. Los usuarios reales nunca ven un puzzle.", FR: "Les signaux comportementaux passifs détectent silencieusement les bots. Notez chaque soumission — ne déclenchez un CAPTCHA que pour le petit pourcentage suspect. Les vrais utilisateurs ne voient jamais de puzzle.", DE: "Passive Verhaltenssignale erkennen Bots still. Bewerten Sie jede Einreichung — lösen Sie CAPTCHA nur für den kleinen verdächtigen Prozentsatz aus. Echte Nutzer sehen nie ein Rätsel."},

	// ── Home — OWASP ───────────────────────────────────────────────────────
	"home.owasp.eyebrow":    {EN: "Threat coverage", ES: "Cobertura de amenazas", FR: "Couverture des menaces", DE: "Bedrohungsabdeckung"},
	"home.owasp.title":      {EN: "OWASP Top 10:2021 Alignment", ES: "Alineación con OWASP Top 10:2021", FR: "Alignement OWASP Top 10:2021", DE: "OWASP Top 10:2021 Ausrichtung"},
	"home.owasp.desc":       {EN: "Client-side defences that complement your server-side security, mapped against the", ES: "Defensas del lado del cliente que complementan tu seguridad del lado del servidor, mapeadas contra el", FR: "Défenses côté client qui complètent votre sécurité côté serveur, mappées contre le", DE: "Client-seitige Abwehrmaßnahmen, die Ihre server-seitige Sicherheit ergänzen, abgebildet auf das"},
	"home.owasp.disclaimer": {EN: "Secure-UI provides client-side defences as part of a defence-in-depth strategy. Server-side validation, authentication, and encryption remain essential.", ES: "Secure-UI proporciona defensas del lado del cliente como parte de una estrategia de defensa en profundidad. La validación, autenticación y cifrado del lado del servidor siguen siendo esenciales.", FR: "Secure-UI fournit des défenses côté client dans le cadre d'une stratégie de défense en profondeur. La validation, l'authentification et le chiffrement côté serveur restent essentiels.", DE: "Secure-UI bietet client-seitige Abwehrmaßnahmen als Teil einer Defense-in-Depth-Strategie. Server-seitige Validierung, Authentifizierung und Verschlüsselung bleiben unerlässlich."},

	// ── Home — Code / SWC ──────────────────────────────────────────────────
	"home.code.eyebrow":           {EN: "Integration", ES: "Integración", FR: "Intégration", DE: "Integration"},
	"home.code.title":             {EN: "Security Without Complexity", ES: "Seguridad Sin Complejidad", FR: "Sécurité Sans Complexité", DE: "Sicherheit ohne Komplexität"},
	"home.code.desc":              {EN: "One tag. No configuration. Secure by default. Native HTML elements — every framework, or no framework at all.", ES: "Una etiqueta. Sin configuración. Seguro por defecto. Elementos HTML nativos — cualquier framework, o ninguno.", FR: "Une balise. Zéro configuration. Sécurisé par défaut. Éléments HTML natifs — tout framework, ou aucun.", DE: "Ein Tag. Keine Konfiguration. Standardmäßig sicher. Native HTML-Elemente — jedes Framework oder keines."},
	"home.swc.one_script.title":   {EN: "One script tag", ES: "Una etiqueta de script", FR: "Une balise script", DE: "Ein Script-Tag"},
	"home.swc.one_script.desc":    {EN: "Import once. Every component self-registers. No build step, no bundler config, no peer dependencies to reconcile.", ES: "Importa una vez. Cada componente se registra solo. Sin paso de compilación, sin configuración de bundler, sin dependencias de pares.", FR: "Importez une fois. Chaque composant s'enregistre automatiquement. Aucune étape de build, aucune config de bundler.", DE: "Einmal importieren. Jede Komponente registriert sich selbst. Kein Build-Schritt, keine Bundler-Konfiguration."},
	"home.swc.agnostic.title":     {EN: "Framework agnostic", ES: "Agnóstico de framework", FR: "Indépendant du framework", DE: "Framework-agnostisch"},
	"home.swc.agnostic.desc":      {EN: "Built on the W3C Custom Elements standard. React, Vue, Angular, Svelte, and server-rendered HTML all treat them identically.", ES: "Construido sobre el estándar W3C Custom Elements. React, Vue, Angular, Svelte y HTML renderizado en servidor los tratan de forma idéntica.", FR: "Basé sur le standard W3C Custom Elements. React, Vue, Angular, Svelte et le HTML rendu côté serveur les traitent de façon identique.", DE: "Basierend auf dem W3C Custom Elements Standard. React, Vue, Angular, Svelte und server-seitig gerendertes HTML behandeln sie identisch."},
	"home.swc.secure.title":       {EN: "Secure by default", ES: "Seguro por defecto", FR: "Sécurisé par défaut", DE: "Standardmäßig sicher"},
	"home.swc.secure.desc":        {EN: "CSRF injection, XSS sanitization, input validation, and audit logging are active from the first render. No flags to set.", ES: "La inyección CSRF, la sanitización XSS, la validación de entradas y el registro de auditoría están activos desde el primer renderizado. Sin flags que configurar.", FR: "L'injection CSRF, la désinfection XSS, la validation des entrées et la journalisation d'audit sont actives dès le premier rendu. Aucun indicateur à configurer.", DE: "CSRF-Injektion, XSS-Sanitierung, Eingabevalidierung und Audit-Logging sind ab dem ersten Rendering aktiv. Keine Flags zu setzen."},
	"home.swc.progressive.title":  {EN: "Progressive enhancement", ES: "Mejora progresiva", FR: "Amélioration progressive", DE: "Progressive Verbesserung"},
	"home.swc.progressive.desc":   {EN: "Server renders native HTML fallbacks. The component upgrades on connect — forms submit correctly with or without JavaScript.", ES: "El servidor renderiza HTML nativo como fallback. El componente se actualiza al conectarse — los formularios se envían correctamente con o sin JavaScript.", FR: "Le serveur rend des fallbacks HTML natifs. Le composant se met à niveau à la connexion — les formulaires se soumettent correctement avec ou sans JavaScript.", DE: "Der Server rendert native HTML-Fallbacks. Die Komponente wird beim Verbinden aktualisiert — Formulare werden korrekt mit oder ohne JavaScript abgesendet."},
	"home.swc.frameworks_label":   {EN: "Works in every environment", ES: "Funciona en cualquier entorno", FR: "Fonctionne dans tous les environnements", DE: "Funktioniert in jeder Umgebung"},

	// ── Home — Telemetry ───────────────────────────────────────────────────
	"home.tel.badge":    {EN: "Built-in Behavioral Intelligence", ES: "Inteligencia de comportamiento integrada", FR: "Intelligence comportementale intégrée", DE: "Integrierte Verhaltensintelligenz"},
	"home.tel.title":    {EN: "Bot Detection Without", ES: "Detección de Bots Sin", FR: "Détection de Bots Sans", DE: "Bot-Erkennung Ohne"},
	"home.tel.title_em": {EN: "the Vendor Tax", ES: "el Coste del Proveedor", FR: "les Frais Fournisseur", DE: "die Anbietergebühr"},
	"home.tel.desc":     {EN: "secure-telemetry-provider collects HMAC-signed behavioral signals on every form submission. Score submissions silently — serve CAPTCHA only to high-risk requests, or skip it entirely for low-risk traffic. No third-party SDKs. No per-transaction fees. Your data, your rules.", ES: "secure-telemetry-provider recopila señales de comportamiento firmadas con HMAC en cada envío de formulario. Puntúa envíos silenciosamente — sirve CAPTCHA solo a solicitudes de alto riesgo. Sin SDKs de terceros. Sin tarifas por transacción. Tus datos, tus reglas.", FR: "secure-telemetry-provider collecte des signaux comportementaux signés HMAC à chaque soumission de formulaire. Notez silencieusement — servez CAPTCHA uniquement aux requêtes à haut risque. Aucun SDK tiers. Aucun frais par transaction. Vos données, vos règles.", DE: "secure-telemetry-provider sammelt HMAC-signierte Verhaltenssignale bei jeder Formularübermittlung. Bewerte Einreichungen still — zeige CAPTCHA nur bei Hochrisiko-Anfragen. Keine Drittanbieter-SDKs. Keine Transaktionsgebühren. Ihre Daten, Ihre Regeln."},
	"home.tel.cta":      {EN: "See how it works", ES: "Ver cómo funciona", FR: "Voir comment ça fonctionne", DE: "So funktioniert es"},

	// ── Home — Theming ─────────────────────────────────────────────────────
	"home.theme.eyebrow": {EN: "Theming", ES: "Temas", FR: "Thèmes", DE: "Design"},
	"home.theme.title":   {EN: "Complete Theming Control", ES: "Control total de temas", FR: "Contrôle total des thèmes", DE: "Vollständige Design-Kontrolle"},
	"home.theme.desc":    {EN: "CSS custom properties as design tokens. Override globally, per component, or per instance. Five built-in presets — or build your own.", ES: "Propiedades CSS personalizadas como tokens de diseño. Sobreescribe globalmente, por componente o por instancia. Cinco presets integrados — o crea los tuyos.", FR: "Propriétés CSS personnalisées comme tokens de design. Surcharge globale, par composant ou par instance. Cinq presets intégrés — ou créez les vôtres.", DE: "CSS Custom Properties als Design-Tokens. Global, pro Komponente oder pro Instanz überschreiben. Fünf integrierte Presets — oder erstellen Sie Ihre eigenen."},
	"home.theme.cta":     {EN: "Explore full theming guide", ES: "Explorar guía completa de temas", FR: "Explorer le guide de thèmes complet", DE: "Vollständige Design-Anleitung erkunden"},

	// ── Components index ───────────────────────────────────────────────────
	"ci.eyebrow":      {EN: "Security-First Web Components", ES: "Componentes web con seguridad prioritaria", FR: "Composants web axés sur la sécurité", DE: "Sicherheitsorientierte Web-Komponenten"},
	"ci.title_line1":  {EN: "Nine components.", ES: "Nueve componentes.", FR: "Neuf composants.", DE: "Neun Komponenten."},
	"ci.title_line2":  {EN: "Zero trust.", ES: "Confianza cero.", FR: "Zéro confiance.", DE: "Null Vertrauen."},
	"ci.subtitle":     {EN: "Security-hardened Custom Elements with XSS prevention, CSRF protection, and audit logging on by default. Any framework. Any stack.", ES: "Custom Elements con seguridad reforzada con prevención XSS, protección CSRF y registro de auditoría activados por defecto. Cualquier framework. Cualquier stack.", FR: "Custom Elements sécurisés avec prévention XSS, protection CSRF et journalisation d'audit activées par défaut. Tout framework. Toute stack.", DE: "Sicherheitsgehärtete Custom Elements mit XSS-Prävention, CSRF-Schutz und Audit-Logging standardmäßig aktiviert. Jedes Framework. Jeder Stack."},
	"ci.stat.components": {EN: "Components", ES: "Componentes", FR: "Composants", DE: "Komponenten"},
	"ci.stat.tiers":      {EN: "Security Tiers", ES: "Niveles de seguridad", FR: "Niveaux de sécurité", DE: "Sicherheitsstufen"},
	"ci.stat.deps":       {EN: "Dependencies", ES: "Dependencias", FR: "Dépendances", DE: "Abhängigkeiten"},
	"ci.stat.badge":      {EN: "Framework Agnostic", ES: "Agnóstico de Framework", FR: "Indépendant du Framework", DE: "Framework-Agnostisch"},
	"ci.fw.title":        {EN: "Works everywhere.", ES: "Funciona en todas partes.", FR: "Fonctionne partout.", DE: "Funktioniert überall."},
	"ci.fw.desc":         {EN: "Built on the W3C Custom Elements v1 specification — real HTML elements with no virtual DOM, no framework runtime, no build step. Security enforcement lives inside the Shadow DOM and cannot be bypassed by the host application.", ES: "Construido sobre la especificación W3C Custom Elements v1 — elementos HTML reales sin DOM virtual, sin runtime de framework, sin paso de compilación. La aplicación de seguridad vive dentro del Shadow DOM y no puede ser eludida por la aplicación anfitriona.", FR: "Basé sur la spécification W3C Custom Elements v1 — de vrais éléments HTML sans DOM virtuel, sans runtime de framework, sans étape de build. L'application de la sécurité vit dans le Shadow DOM et ne peut pas être contournée par l'application hôte.", DE: "Basierend auf der W3C Custom Elements v1 Spezifikation — echte HTML-Elemente ohne virtuelles DOM, ohne Framework-Runtime, ohne Build-Schritt. Die Sicherheitsdurchsetzung lebt im Shadow DOM und kann nicht umgangen werden."},

	"ci.card.input.desc":     {EN: "Security-hardened text input with XSS prevention, type validation, and audit logging.", ES: "Entrada de texto con seguridad reforzada, prevención XSS, validación de tipo y registro de auditoría.", FR: "Champ texte sécurisé avec prévention XSS, validation de type et journalisation d'audit.", DE: "Sicherheitsgehärtetes Texteingabefeld mit XSS-Prävention, Typvalidierung und Audit-Logging."},
	"ci.card.select.desc":    {EN: "Dropdown select with option injection prevention and value allowlist enforcement.", ES: "Selector desplegable con prevención de inyección de opciones y cumplimiento de lista blanca de valores.", FR: "Menu déroulant avec prévention d'injection d'options et application de la liste blanche des valeurs.", DE: "Dropdown-Auswahl mit Optionsinjektions-Prävention und Wertelisten-Durchsetzung."},
	"ci.card.textarea.desc":  {EN: "Multi-line text area with content sanitization and paste attack prevention.", ES: "Área de texto multilínea con sanitización de contenido y prevención de ataques por pegado.", FR: "Zone de texte multi-lignes avec désinfection du contenu et prévention des attaques par collage.", DE: "Mehrzeiliges Textfeld mit Inhaltssanitierung und Schutz vor Einfüge-Angriffen."},
	"ci.card.form.desc":      {EN: "Form wrapper with automatic CSRF token injection, submission audit logging, and behavioral telemetry integration.", ES: "Envoltorio de formulario con inyección automática de token CSRF, registro de auditoría y integración de telemetría de comportamiento.", FR: "Wrapper de formulaire avec injection automatique de jetons CSRF, journalisation d'audit et intégration de la télémétrie comportementale.", DE: "Formular-Wrapper mit automatischer CSRF-Token-Injektion, Übermittlungs-Audit-Logging und Verhaltens-Telemetrie-Integration."},
	"ci.card.upload.desc":    {EN: "File upload with MIME type validation, magic number verification, and size enforcement.", ES: "Carga de archivos con validación de tipo MIME, verificación de número mágico y cumplimiento de tamaño.", FR: "Upload de fichiers avec validation du type MIME, vérification des octets magiques et contrôle de taille.", DE: "Datei-Upload mit MIME-Typ-Validierung, Magic-Number-Verifizierung und Größenbeschränkung."},
	"ci.card.datetime.desc":  {EN: "Date and time picker with input sanitization, range enforcement, and timezone handling.", ES: "Selector de fecha y hora con sanitización de entrada, cumplimiento de rango y gestión de zona horaria.", FR: "Sélecteur de date et heure avec désinfection des entrées, contrôle de plage et gestion des fuseaux horaires.", DE: "Datums- und Zeitauswahl mit Eingabe-Sanitierung, Bereichsdurchsetzung und Zeitzonenbehandlung."},
	"ci.card.table.desc":     {EN: "Data table with XSS-safe rendering, sort/filter sanitization, and column injection prevention.", ES: "Tabla de datos con renderizado seguro contra XSS, sanitización de ordenación/filtrado y prevención de inyección de columnas.", FR: "Tableau de données avec rendu sécurisé XSS, désinfection du tri/filtre et prévention d'injection de colonnes.", DE: "Datentabelle mit XSS-sicherem Rendering, Sortier-/Filter-Sanitierung und Spalteninjektions-Prävention."},
	"ci.card.payment.desc":   {EN: "Payment card input with Luhn validation, 3D preview, card type detection, and PAN/CVC protection.", ES: "Entrada de tarjeta de pago con validación Luhn, vista previa 3D, detección de tipo de tarjeta y protección PAN/CVC.", FR: "Champ de carte de paiement avec validation Luhn, aperçu 3D, détection du type de carte et protection PAN/CVC.", DE: "Zahlungskarteneingabe mit Luhn-Validierung, 3D-Vorschau, Kartentypenerkennung und PAN/CVC-Schutz."},
	"ci.card.telemetry.desc": {EN: "Wraps a form to collect bot-detection signals and attach a HMAC-signed envelope to every submission.", ES: "Envuelve un formulario para recopilar señales de detección de bots y adjuntar un sobre firmado con HMAC a cada envío.", FR: "Enveloppe un formulaire pour collecter des signaux de détection de bots et joindre une enveloppe signée HMAC à chaque soumission.", DE: "Umschließt ein Formular, um Bot-Erkennungssignale zu sammeln und jedem Submit einen HMAC-signierten Umschlag anzuhängen."},

	// ── Documentation ──────────────────────────────────────────────────────
	"docs.title":    {EN: "Documentation", ES: "Documentación", FR: "Documentation", DE: "Dokumentation"},
	"docs.subtitle": {EN: "Complete reference for Secure-UI web components. Security-first form elements with built-in validation, XSS prevention, and audit logging.", ES: "Referencia completa para los componentes web de Secure-UI. Elementos de formulario con seguridad prioritaria, validación integrada, prevención XSS y registro de auditoría.", FR: "Référence complète pour les composants web Secure-UI. Éléments de formulaire axés sur la sécurité avec validation intégrée, prévention XSS et journalisation d'audit.", DE: "Vollständige Referenz für Secure-UI Web-Komponenten. Sicherheitsorientierte Formularelemente mit integrierter Validierung, XSS-Prävention und Audit-Logging."},

	"docs.qs.title": {EN: "Quick Start", ES: "Inicio rápido", FR: "Démarrage rapide", DE: "Schnellstart"},
	"docs.qs.desc":  {EN: "Add Secure-UI components to your project by importing the component library. Components self-register and are immediately available for use.", ES: "Añade componentes Secure-UI a tu proyecto importando la biblioteca de componentes. Los componentes se registran solos y están disponibles de inmediato.", FR: "Ajoutez des composants Secure-UI à votre projet en important la bibliothèque de composants. Les composants s'enregistrent automatiquement et sont immédiatement utilisables.", DE: "Fügen Sie Secure-UI-Komponenten zu Ihrem Projekt hinzu, indem Sie die Komponentenbibliothek importieren. Komponenten registrieren sich selbst und sind sofort verfügbar."},

	"docs.tiers.title": {EN: "Security Tiers", ES: "Niveles de seguridad", FR: "Niveaux de sécurité", DE: "Sicherheitsstufen"},
	"docs.tiers.desc":  {EN: "Every component supports four security tiers that control validation strictness, visual indicators, and security features. Choose the appropriate tier based on the sensitivity of the data being collected.", ES: "Cada componente admite cuatro niveles de seguridad que controlan la estrictez de validación, los indicadores visuales y las características de seguridad. Elige el nivel apropiado según la sensibilidad de los datos recopilados.", FR: "Chaque composant prend en charge quatre niveaux de sécurité qui contrôlent la rigueur de validation, les indicateurs visuels et les fonctionnalités de sécurité. Choisissez le niveau approprié en fonction de la sensibilité des données collectées.", DE: "Jede Komponente unterstützt vier Sicherheitsstufen, die die Validierungsstrenge, visuelle Indikatoren und Sicherheitsfunktionen steuern. Wählen Sie die entsprechende Stufe basierend auf der Sensitivität der gesammelten Daten."},

	"docs.tier.public.desc":         {EN: "Standard security for non-sensitive data. Basic validation, autocomplete allowed.", ES: "Seguridad estándar para datos no sensibles. Validación básica, autocompletado permitido.", FR: "Sécurité standard pour les données non sensibles. Validation de base, saisie automatique autorisée.", DE: "Standardsicherheit für nicht sensible Daten. Grundvalidierung, Autovervollständigung erlaubt."},
	"docs.tier.authenticated.desc":  {EN: "For logged-in users. Enhanced validation, session-aware features.", ES: "Para usuarios autenticados. Validación mejorada, funciones con conciencia de sesión.", FR: "Pour les utilisateurs connectés. Validation renforcée, fonctionnalités tenant compte de la session.", DE: "Für angemeldete Benutzer. Erweiterte Validierung, sitzungsbewusste Funktionen."},
	"docs.tier.sensitive.desc":      {EN: "PII and personal data. Masking, no autocomplete, rate limiting.", ES: "PII y datos personales. Enmascaramiento, sin autocompletado, limitación de velocidad.", FR: "IIP et données personnelles. Masquage, pas de saisie automatique, limitation du débit.", DE: "PII und persönliche Daten. Maskierung, kein Autovervollständigen, Ratenbegrenzung."},
	"docs.tier.critical.desc":       {EN: "Passwords, financial data. Maximum security, full audit logging.", ES: "Contraseñas, datos financieros. Seguridad máxima, registro de auditoría completo.", FR: "Mots de passe, données financières. Sécurité maximale, journalisation d'audit complète.", DE: "Passwörter, Finanzdaten. Maximale Sicherheit, vollständiges Audit-Logging."},

	"docs.components.title":         {EN: "Components", ES: "Componentes", FR: "Composants", DE: "Komponenten"},
	"docs.components.desc":          {EN: "Nine security-first web components. Each ships with XSS prevention, validation, and audit logging enabled by default — security is opt-out, not opt-in.", ES: "Nueve componentes web con seguridad prioritaria. Cada uno viene con prevención XSS, validación y registro de auditoría habilitados por defecto — la seguridad es opt-out, no opt-in.", FR: "Neuf composants web axés sur la sécurité. Chacun est livré avec la prévention XSS, la validation et la journalisation d'audit activées par défaut — la sécurité est opt-out, pas opt-in.", DE: "Neun sicherheitsorientierte Web-Komponenten. Jede wird mit XSS-Prävention, Validierung und Audit-Logging standardmäßig aktiviert geliefert — Sicherheit ist Opt-out, nicht Opt-in."},
	"docs.components.form_inputs":   {EN: "Form Inputs", ES: "Entradas de formulario", FR: "Champs de formulaire", DE: "Formulareingaben"},
	"docs.components.orchestration": {EN: "Orchestration", ES: "Orquestación", FR: "Orchestration", DE: "Orchestrierung"},
	"docs.components.display":       {EN: "Display", ES: "Visualización", FR: "Affichage", DE: "Anzeige"},

	"docs.card.input.desc":     {EN: "Text, email, password, and number inputs with XSS prevention and per-tier validation rules.", ES: "Entradas de texto, email, contraseña y número con prevención XSS y reglas de validación por nivel.", FR: "Entrées de texte, email, mot de passe et nombre avec prévention XSS et règles de validation par niveau.", DE: "Text-, E-Mail-, Passwort- und Zahleneingaben mit XSS-Prävention und stufenweisen Validierungsregeln."},
	"docs.card.select.desc":    {EN: "Dropdown select with allowlist-only option validation and injection prevention.", ES: "Selector desplegable con validación de opciones solo por lista blanca y prevención de inyección.", FR: "Menu déroulant avec validation des options par liste blanche uniquement et prévention d'injection.", DE: "Dropdown-Auswahl mit Allowlist-basierter Optionsvalidierung und Injektionsschutz."},
	"docs.card.textarea.desc":  {EN: "Multi-line text input with content sanitization, character limits, and live count.", ES: "Entrada de texto multilínea con sanitización de contenido, límites de caracteres y contador en vivo.", FR: "Entrée de texte multi-lignes avec désinfection du contenu, limites de caractères et comptage en direct.", DE: "Mehrzeilige Texteingabe mit Inhaltssanitierung, Zeichenlimits und Live-Zähler."},
	"docs.card.datetime.desc":  {EN: "Date, time, and datetime-local inputs with timezone handling and range validation.", ES: "Entradas de fecha, hora y datetime-local con manejo de zona horaria y validación de rango.", FR: "Entrées de date, heure et datetime-local avec gestion des fuseaux horaires et validation de plage.", DE: "Datums-, Zeit- und datetime-local-Eingaben mit Zeitzonenbehandlung und Bereichsvalidierung."},
	"docs.card.upload.desc":    {EN: "File upload with MIME allowlist, size limits, magic-number verification, and scan hook.", ES: "Carga de archivos con lista blanca MIME, límites de tamaño, verificación de número mágico y gancho de escaneo.", FR: "Upload de fichiers avec liste blanche MIME, limites de taille, vérification des octets magiques et hook de scan.", DE: "Datei-Upload mit MIME-Allowlist, Größenlimits, Magic-Number-Verifizierung und Scan-Hook."},
	"docs.card.payment.desc":   {EN: "Payment card input with Luhn validation, card type detection, PAN masking, and 3D flip preview. Tier locked to Critical.", ES: "Entrada de tarjeta de pago con validación Luhn, detección de tipo de tarjeta, enmascaramiento PAN y vista previa 3D. Nivel bloqueado en Crítico.", FR: "Champ de carte de paiement avec validation Luhn, détection du type de carte, masquage PAN et aperçu 3D. Niveau verrouillé en Critique.", DE: "Zahlungskarteneingabe mit Luhn-Validierung, Kartentypenerkennung, PAN-Maskierung und 3D-Vorschau. Stufe auf Kritisch gesperrt."},
	"docs.card.form.desc":      {EN: "Form wrapper with automatic CSRF token injection, coordinated validation, and submission lifecycle events.", ES: "Envoltorio de formulario con inyección automática de token CSRF, validación coordinada y eventos del ciclo de vida de envío.", FR: "Wrapper de formulaire avec injection automatique de jetons CSRF, validation coordonnée et événements du cycle de vie de soumission.", DE: "Formular-Wrapper mit automatischer CSRF-Token-Injektion, koordinierter Validierung und Übermittlungs-Lifecycle-Events."},
	"docs.card.telemetry.desc": {EN: "Wraps a form to collect environmental signals and attach an HMAC-SHA-256 signed envelope to every submission.", ES: "Envuelve un formulario para recopilar señales ambientales y adjuntar un sobre firmado con HMAC-SHA-256 a cada envío.", FR: "Enveloppe un formulaire pour collecter des signaux environnementaux et joindre une enveloppe signée HMAC-SHA-256 à chaque soumission.", DE: "Umschließt ein Formular, um Umgebungssignale zu sammeln und jedem Submit einen HMAC-SHA-256-signierten Umschlag anzuhängen."},
	"docs.card.table.desc":     {EN: "Data table with XSS-safe cell rendering, sanitized sort and filter, and column injection prevention.", ES: "Tabla de datos con renderizado de celdas seguro contra XSS, ordenación y filtrado sanitizados, y prevención de inyección de columnas.", FR: "Tableau de données avec rendu de cellules sécurisé XSS, tri et filtre désinfectés et prévention d'injection de colonnes.", DE: "Datentabelle mit XSS-sicherem Zell-Rendering, sanitierter Sortierung und Filterung sowie Spalteninjektions-Prävention."},

	// ── Login ──────────────────────────────────────────────────────────────
	"login.eyebrow":       {EN: "Secure Authentication", ES: "Autenticación segura", FR: "Authentification sécurisée", DE: "Sichere Authentifizierung"},
	"login.brand_heading": {EN: "Security by design, not by accident.", ES: "Seguridad por diseño, no por accidente.", FR: "Sécurité par conception, pas par accident.", DE: "Sicherheit durch Design, nicht durch Zufall."},
	"login.brand_desc":    {EN: "This demo authenticates against a real session-based backend. Every request is CSRF-protected and rate-limited.", ES: "Esta demo se autentica contra un backend real basado en sesiones. Cada solicitud está protegida con CSRF y limitada en velocidad.", FR: "Cette démo s'authentifie auprès d'un backend réel basé sur les sessions. Chaque requête est protégée par CSRF et limitée en débit.", DE: "Diese Demo authentifiziert sich gegen ein echtes sitzungsbasiertes Backend. Jede Anfrage ist CSRF-geschützt und ratenbegrenzt."},
	"login.feat1":         {EN: "CSRF token validation on every form submit", ES: "Validación de token CSRF en cada envío de formulario", FR: "Validation du jeton CSRF à chaque soumission de formulaire", DE: "CSRF-Token-Validierung bei jedem Formular-Submit"},
	"login.feat2":         {EN: "bcrypt password hashing", ES: "Hash de contraseña con bcrypt", FR: "Hachage de mot de passe bcrypt", DE: "bcrypt-Passwort-Hashing"},
	"login.feat3":         {EN: "Rate-limited login — brute-force protection", ES: "Inicio de sesión con límite de velocidad — protección contra fuerza bruta", FR: "Connexion à débit limité — protection contre la force brute", DE: "Ratenbegrenzte Anmeldung — Brute-Force-Schutz"},
	"login.feat4":         {EN: "Secure session cookies (HttpOnly, SameSite)", ES: "Cookies de sesión seguras (HttpOnly, SameSite)", FR: "Cookies de session sécurisés (HttpOnly, SameSite)", DE: "Sichere Sitzungs-Cookies (HttpOnly, SameSite)"},
	"login.feat5":         {EN: "Audit log on every authentication event", ES: "Registro de auditoría en cada evento de autenticación", FR: "Journal d'audit sur chaque événement d'authentification", DE: "Audit-Log bei jedem Authentifizierungsereignis"},
	"login.title":         {EN: "Sign in", ES: "Iniciar sesión", FR: "Connexion", DE: "Anmelden"},
	"login.subtitle":      {EN: "Access the secure-ui showcase and protected demos.", ES: "Accede al showcase de secure-ui y las demos protegidas.", FR: "Accédez au showcase secure-ui et aux démos protégées.", DE: "Zugang zum Secure-UI-Showcase und geschützten Demos."},
	"login.email":         {EN: "Email", ES: "Correo electrónico", FR: "E-mail", DE: "E-Mail"},
	"login.password":      {EN: "Password", ES: "Contraseña", FR: "Mot de passe", DE: "Passwort"},
	"login.submit":        {EN: "Sign In", ES: "Iniciar sesión", FR: "Se connecter", DE: "Anmelden"},
	"login.no_account":    {EN: "Don't have an account?", ES: "¿No tienes una cuenta?", FR: "Pas encore de compte ?", DE: "Noch kein Konto?"},
	"login.create":        {EN: "Create one", ES: "Crear una", FR: "En créer un", DE: "Jetzt registrieren"},
	"login.csrf":          {EN: "CSRF Protected", ES: "Protegido CSRF", FR: "Protégé CSRF", DE: "CSRF-geschützt"},
	"login.ratelimit":     {EN: "Rate Limited", ES: "Límite de velocidad", FR: "Débit limité", DE: "Ratenbegrenzt"},
	"login.audit":         {EN: "Audit Logged", ES: "Auditoría registrada", FR: "Journalisé", DE: "Audit-protokolliert"},

	// ── Registration ───────────────────────────────────────────────────────
	"reg.eyebrow":       {EN: "Secure Registration", ES: "Registro seguro", FR: "Inscription sécurisée", DE: "Sichere Registrierung"},
	"reg.brand_heading": {EN: "Built for developers who care about security.", ES: "Construido para desarrolladores que se preocupan por la seguridad.", FR: "Conçu pour les développeurs soucieux de la sécurité.", DE: "Für Entwickler, die Sicherheit schätzen."},
	"reg.brand_desc":    {EN: "Registration demonstrates server-side input validation, constraint enforcement, and secure credential storage with no client-side secrets.", ES: "El registro demuestra la validación de entradas del lado del servidor, el cumplimiento de restricciones y el almacenamiento seguro de credenciales sin secretos del lado del cliente.", FR: "L'inscription démontre la validation des entrées côté serveur, l'application des contraintes et le stockage sécurisé des identifiants sans secrets côté client.", DE: "Die Registrierung demonstriert server-seitige Eingabevalidierung, Constraint-Durchsetzung und sichere Anmeldedaten-Speicherung ohne client-seitige Geheimnisse."},
	"reg.feat1":         {EN: "Server-side validation on every field", ES: "Validación del lado del servidor en cada campo", FR: "Validation côté serveur sur chaque champ", DE: "Server-seitige Validierung bei jedem Feld"},
	"reg.feat2":         {EN: "Password hashed with bcrypt — never stored in plain text", ES: "Contraseña hasheada con bcrypt — nunca almacenada en texto plano", FR: "Mot de passe haché avec bcrypt — jamais stocké en texte clair", DE: "Passwort mit bcrypt gehasht — niemals im Klartext gespeichert"},
	"reg.feat3":         {EN: "Input sanitised with bluemonday strict policy", ES: "Entradas sanitizadas con la política estricta de bluemonday", FR: "Entrées désinfectées avec la politique stricte de bluemonday", DE: "Eingaben mit bluemonday-Striktrichtlinie sanitiert"},
	"reg.feat4":         {EN: "CSRF token required on every form submission", ES: "Token CSRF requerido en cada envío de formulario", FR: "Jeton CSRF requis à chaque soumission de formulaire", DE: "CSRF-Token bei jeder Formularübermittlung erforderlich"},
	"reg.feat5":         {EN: "Duplicate email detection without timing attacks", ES: "Detección de email duplicado sin ataques de tiempo", FR: "Détection des emails en double sans attaques temporelles", DE: "Duplikat-E-Mail-Erkennung ohne Timing-Angriffe"},
	"reg.title":         {EN: "Create account", ES: "Crear cuenta", FR: "Créer un compte", DE: "Konto erstellen"},
	"reg.subtitle":      {EN: "Try the secure registration flow with real-time validation.", ES: "Prueba el flujo de registro seguro con validación en tiempo real.", FR: "Essayez le flux d'inscription sécurisé avec validation en temps réel.", DE: "Probieren Sie den sicheren Registrierungsablauf mit Echtzeit-Validierung."},
	"reg.first_name":    {EN: "First Name", ES: "Nombre", FR: "Prénom", DE: "Vorname"},
	"reg.last_name":     {EN: "Last Name", ES: "Apellido", FR: "Nom de famille", DE: "Nachname"},
	"reg.email":         {EN: "Email", ES: "Correo electrónico", FR: "E-mail", DE: "E-Mail"},
	"reg.password":      {EN: "Password", ES: "Contraseña", FR: "Mot de passe", DE: "Passwort"},
	"reg.confirm":       {EN: "Confirm Password", ES: "Confirmar contraseña", FR: "Confirmer le mot de passe", DE: "Passwort bestätigen"},
	"reg.terms":         {EN: "I agree to the Terms of Service and Privacy Policy", ES: "Acepto los Términos de servicio y la Política de privacidad", FR: "J'accepte les Conditions d'utilisation et la Politique de confidentialité", DE: "Ich stimme den Nutzungsbedingungen und der Datenschutzrichtlinie zu"},
	"reg.submit":        {EN: "Create Account", ES: "Crear cuenta", FR: "Créer le compte", DE: "Konto erstellen"},
	"reg.have_account":  {EN: "Already have an account?", ES: "¿Ya tienes una cuenta?", FR: "Déjà un compte ?", DE: "Bereits ein Konto?"},
	"reg.signin":        {EN: "Sign in", ES: "Iniciar sesión", FR: "Se connecter", DE: "Anmelden"},
	"reg.csrf":          {EN: "CSRF Protected", ES: "Protegido CSRF", FR: "Protégé CSRF", DE: "CSRF-geschützt"},
	"reg.validated":     {EN: "Validated", ES: "Validado", FR: "Validé", DE: "Validiert"},
	"reg.hashed":        {EN: "bcrypt Hashed", ES: "Hash bcrypt", FR: "Haché bcrypt", DE: "bcrypt-gehasht"},
}
